//
//  File.swift
//  
//
//  Created by James Rochabrun on 11/9/23.
//

import Foundation

public struct FunctionCall: Decodable {
   
   /// The arguments to call the function with, as generated by the model in JSON format. Note that the model does not always generate valid JSON, and may hallucinate parameters not defined by your function schema. Validate the arguments in your code before calling your function.
   public let arguments: String
   /// The name of the function to call.
   public let name: String?
}
