# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: CI tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test_macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Get swift version
      run: swift --version
    - name: Build
      run: swift build -q
    - name: Run tests
      run: swift test -q

  build_and_test_linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - image: swift:6.0.1-jammy
            dependencies: locked
          - image: swift:6.2-jammy
            dependencies: latest
    container:
      image: ${{ matrix.image }}
    steps:
    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y curl git
    - uses: actions/checkout@v4
    - name: Get swift version
      run: swift --version
    - name: Resolve current compatible dependencies
      if: matrix.dependencies == 'latest'
      run: swift package update
    - name: Clean build
      run: |
        swift package clean
        swift build -q --force-resolved-versions
    - name: Run tests
      run: swift test -q --force-resolved-versions

  lint:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Homebrew
      id: set-up-homebrew
      uses: Homebrew/actions/setup-homebrew@master
    - name: Install swiftformat
      run: brew install swiftformat
    - name: Check formatting
      run: swiftformat --config rules.swiftformat --lint .
